server.address=127.0.0.1
server.port=${SERVER_PORT:8080}
spring.application.name=reference-service
server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never
